/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /mnt/c/Users/Alphatron1999/Desktop/Compiler/MiniNim/nimcache/test.o /mnt/c/Users/Alphatron1999/Desktop/Compiler/MiniNim/nimcache/test.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, app_JmPk52BIXyvUDvMrHVpM3g)(NI a, NI b, NI c);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, testDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NI a_MKOwYvPH6MkTSfJQoSvUmg;
NI c_5aKKa0MthZHIAhTjV62n8A;
NI d_GWj0w9ciK385zt9cJNLS5eAQ;
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ __klVv0FOOLLqawDRb5EABWA;
NI ax_5hBjqTNJ9aAgrilkHbj2JVg;
NI x_9bf4p1FLrvkXIchOKUUtCcw;
NI i_vyCYEvJNp9c9b1bD8JVdQqrQ;
NIM_CONST tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ TM_ipcYmBC9bj9a1BW35ABoB1Kw_2 = {((NI) 0),
((NI) 1)}
;
NIM_CONST tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ TM_ipcYmBC9bj9a1BW35ABoB1Kw_3 = {((NI) 1),
((NI) 0)}
;
STRING_LITERAL(TM_ipcYmBC9bj9a1BW35ABoB1Kw_4, "0", 1);
STRING_LITERAL(TM_ipcYmBC9bj9a1BW35ABoB1Kw_6, "2", 1);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(NI, app_JmPk52BIXyvUDvMrHVpM3g)(NI a, NI b, NI c) {
	NI result;
	nimfr_("app", "test.nim");
{	result = (NI)0;
	nimln_(2, "test.nim");
	result = ((NI) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	testDatInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("test", "test.nim");
	{
		nimln_(3, "test.nim");
		a_MKOwYvPH6MkTSfJQoSvUmg = app_JmPk52BIXyvUDvMrHVpM3g(((NI) 1), ((NI) 2), ((NI) 3));
		nimln_(5, "test.nim");
		c_5aKKa0MthZHIAhTjV62n8A = TM_ipcYmBC9bj9a1BW35ABoB1Kw_2.Field0;
		d_GWj0w9ciK385zt9cJNLS5eAQ = TM_ipcYmBC9bj9a1BW35ABoB1Kw_2.Field1;
		nimln_(6, "test.nim");
		__klVv0FOOLLqawDRb5EABWA = TM_ipcYmBC9bj9a1BW35ABoB1Kw_3;
		d_GWj0w9ciK385zt9cJNLS5eAQ = __klVv0FOOLLqawDRb5EABWA.Field0;
		c_5aKKa0MthZHIAhTjV62n8A = __klVv0FOOLLqawDRb5EABWA.Field1;
		nimln_(7, "test.nim");
		ax_5hBjqTNJ9aAgrilkHbj2JVg = ((NI) 2);
		nimln_(9, "test.nim");
		printf("%s\012", ((NimStringDesc*) &TM_ipcYmBC9bj9a1BW35ABoB1Kw_4)? (((NimStringDesc*) &TM_ipcYmBC9bj9a1BW35ABoB1Kw_4))->data:"nil");
		fflush(stdout);
		nimln_(10, "test.nim");
		x_9bf4p1FLrvkXIchOKUUtCcw = ((NI) 2);
		{
			NI res;
			nimln_(1986, "system.nim");
			res = ((NI) 0);
			{
				nimln_(1987, "system.nim");
				while (1) {
					NimStringDesc* T9_;
					NI TM_ipcYmBC9bj9a1BW35ABoB1Kw_5;
					if (!(res <= ((NI) 3))) goto LA4;
					nimln_(1988, "system.nim");
					i_vyCYEvJNp9c9b1bD8JVdQqrQ = res;
					nimln_(12, "test.nim");
					{
						if (!(i_vyCYEvJNp9c9b1bD8JVdQqrQ == ((NI) 2))) goto LA7_;
						nimln_(13, "test.nim");
						goto LA2;
					}
					LA7_: ;
					nimln_(14, "test.nim");
					T9_ = (NimStringDesc*)0;
					T9_ = nimIntToStr(x_9bf4p1FLrvkXIchOKUUtCcw);
					printf("%s\012", T9_? (T9_)->data:"nil");
					fflush(stdout);
					nimln_(1989, "system.nim");
					TM_ipcYmBC9bj9a1BW35ABoB1Kw_5 = addInt(res, ((NI) 1));
					res = (NI)(TM_ipcYmBC9bj9a1BW35ABoB1Kw_5);
				} LA4: ;
			}
		} LA2: ;
		nimln_(15, "test.nim");
		printf("%s\012", ((NimStringDesc*) &TM_ipcYmBC9bj9a1BW35ABoB1Kw_6)? (((NimStringDesc*) &TM_ipcYmBC9bj9a1BW35ABoB1Kw_6))->data:"nil");
		fflush(stdout);
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, testDatInit000)(void) {
}

